name: build-matrix

description: "Determine the build matrix"

outputs:
  matrix:
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Determine the build matrix
      id: matrix
      shell: bash
      run: |
        echo "matrix=$(
        cat <<EOF | yq -o json --no-colors | jq -c -r -M '.matrix'
        matrix:
          RUST: ["", "rust"]
          LLVM: ["", "llvm15", "llvmdev"]
          CUDA: ["", "cuda11.8", "cuda12.0"]
          NVHPC: ["", "nvhpc22.11"]
          MAMBA: ["", "mambaforge"]
          exclude:
            - { RUST: "rust", NVHPC: "nvhpc22.11" }
            - { RUST: "rust", CUDA: "", LLVM: "", NVHPC: "" }
            - { RUST: "rust", CUDA: "", LLVM: "llvm15", MAMBA: "" }
            - { RUST: "rust", CUDA: "", LLVM: "llvmdev", MAMBA: "" }
            - { NVHPC: "nvhpc22.11",        MAMBA: "mambaforge" }
            - { CUDA: "",         LLVM: "", MAMBA: "mambaforge" }
            - { CUDA: "cuda11.8", LLVM: "", NVHPC: "nvhpc22.11" }
            - { CUDA: "cuda12.0", LLVM: "", NVHPC: "nvhpc22.11" }
        EOF
        )" | tee -a $GITHUB_OUTPUT;
