name: Publish images to Docker Hub

on:
  workflow_dispatch:

concurrency:
  group: publish-images-to-dockerhub-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build-matrix:
    name: Matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Determine the build matrix
        id: matrix
        uses: ./.github/actions/build-matrix

  publish-images:
    name: Publish
    needs: build-matrix
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Determine devcontainer image name and tag
        uses: ./.github/actions/image-name-and-tag
        id: image-and-tag
        with:
          CUDA: "${{ matrix.CUDA }}"
          LLVM: "${{ matrix.LLVM }}"
          NVHPC: "${{ matrix.NVHPC }}"
          MAMBA: "${{ matrix.MAMBA }}"

      - name: Free up disk space
        uses: ./.github/actions/free-disk-space
        with:
          home: "${{ env.HOME }}"
          tool_cache: "${{ runner.tool_cache }}"

      - name: Publish image to Docker Hub
        uses: ./.github/actions/publish-to-dockerhub
        with:
          tag: ${{ steps.image-and-tag.outputs.tag }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
