name: Publish images

on:
  pull_request:
  workflow_dispatch:

jobs:
  publish-images:
    name: Publish image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ARCH: ["amd64", "arm64"]
        CUDA: ["", "11.8", "12.0"]
        LLVM: ["", "13", "14", "15", "dev"]
        NVHPC: ["", "22.11"]
        MAMBA: ["", "mambaforge"]
    steps:
      - name: Checkout stdexec
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Report image name and tag
        shell: bash
        env:
          CUDA: "${{ matrix.CUDA }}"
          LLVM: "${{ matrix.LLVM }}"
          NVHPC: "${{ matrix.NVHPC }}"
        run: |
          repo_cuda=${CUDA:+"-cuda"}
          repo_llvm=${LLVM:+"-llvm"}
          repo_nvhpc=${NVHPC:+"-nvhpc"}
          repo_mamba=${MAMBA:+"-mambaforge"}
          repo="cmake-ninja-sccache${repo_llvm}${repo_cuda}${repo_mamba}${repo_nvhpc}"

          if [[ ! -d "src/${repo}" ]]; then exit 0; fi

          tag_cuda=${CUDA:+"${repo_cuda}${CUDA}"}
          tag_llvm=${LLVM:+"${repo_llvm}${LLVM}"}
          tag_nvhpc=${NVHPC:+"${repo_nvhpc}${NVHPC}"}
          tag="${tag_llvm}${tag_cuda}${tag_nvhpc}"

          echo "$repo:${tag:+$tag-}${{ matrix.ARCH }}"
