name: Build

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-images-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build-matrix:
    name: Matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Determine the build matrix
        id: matrix
        uses: ./.github/actions/build-matrix

  build-images:
    name: Build
    needs: build-matrix
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Determine devcontainer dir and image tag
        uses: ./.github/actions/image-dir-and-tag
        id: image-dir-and-tag
        with:
          CUDA: "${{ matrix.CUDA }}"
          LLVM: "${{ matrix.LLVM }}"
          NVHPC: "${{ matrix.NVHPC }}"
          MAMBA: "${{ matrix.MAMBA }}"

      - name: Free up disk space
        uses: ./.github/actions/free-disk-space
        with:
          home: "${{ env.HOME }}"
          tool_cache: "${{ runner.tool_cache }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          use: true

      - if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build devcontainer
        uses: devcontainers/ci@v0.2
        with:
          push: filter
          skipContainerUserIdUpdate: true
          refFilterForPush: refs/heads/main
          eventFilterForPush: workflow_dispatch
          imageTag: ${{ steps.image-dir-and-tag.outputs.tag }}
          subFolder: src/${{ steps.image-dir-and-tag.outputs.dir }}
          platform: linux/amd64,linux/arm64
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}:${{ steps.image-dir-and-tag.outputs.tag }}

  push-to-dockerhub:
    name: Push images to Docker Hub
    needs: build-images
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/dockerhub.yml
    secrets: inherit
