name: Publish images

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: publish-images-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish-images:
    name: Publish image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CUDA: ["", "cuda11.8", "cuda12.0"]
        LLVM: ["", "llvm13", "llvm14", "llvm15", "llvmdev"]
        NVHPC: ["", "nvhpc22.11"]
        MAMBA: [""]
        exclude:
          - { CUDA: "cuda11.8", LLVM: "", NVHPC: "nvhpc22.11" }
          - { CUDA: "cuda11.8", LLVM: "", NVHPC: "nvhpc22.11" }
          - { CUDA: "cuda11.8", LLVM: "", NVHPC: "nvhpc22.11" }
          - { CUDA: "cuda11.8", LLVM: "", NVHPC: "nvhpc22.11" }
          - { CUDA: "cuda12.0", LLVM: "", NVHPC: "nvhpc22.11" }
          - { CUDA: "cuda12.0", LLVM: "", NVHPC: "nvhpc22.11" }
          - { CUDA: "cuda12.0", LLVM: "", NVHPC: "nvhpc22.11" }
          - { CUDA: "cuda12.0", LLVM: "", NVHPC: "nvhpc22.11" }
        include:
          - { CUDA: "", LLVM: "llvm13", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "", LLVM: "llvm14", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "", LLVM: "llvm15", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "", LLVM: "llvmdev", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda11.8", LLVM: "llvm13", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda11.8", LLVM: "llvm14", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda11.8", LLVM: "llvm15", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda11.8", LLVM: "llvmdev", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda12.0", LLVM: "llvm13", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda12.0", LLVM: "llvm14", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda12.0", LLVM: "llvm15", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "cuda12.0", LLVM: "llvmdev", NVHPC: "", MAMBA: "mambaforge" }
    steps:
      - name: Checkout stdexec
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Check repo name
        shell: bash
        env:
          CUDA: "${{ matrix.CUDA }}"
          LLVM: "${{ matrix.LLVM }}"
          NVHPC: "${{ matrix.NVHPC }}"
          MAMBA: "${{ matrix.MAMBA }}"
        run: |
          cuda=${CUDA:+"-cuda"}
          llvm=${LLVM:+"-llvm"}
          nvhpc=${NVHPC:+"-nvhpc"}
          mamba=${MAMBA:+"-mambaforge"}
          dir="cmake-ninja-sccache${llvm}${cuda}${mamba}${nvhpc}"

          if [[ ! -d "./src/${dir}" ]]; then
            echo "skipping because ! -d ./src/${dir}";
            echo "build_image=0" >> $GITHUB_ENV;
            exit 0;
          fi

          echo "build_image=1" >> $GITHUB_ENV;

          cuda=${CUDA:+"-${CUDA}"}
          llvm=${LLVM:+"-${LLVM}"}
          nvhpc=${NVHPC:+"-${NVHPC}"}
          mamba=${MAMBA:+"-mambaforge"}
          tag="cmake-ninja-sccache${llvm}${cuda}${nvhpc}${mamba}"
          tag="${tag:-latest}"

          echo "dir=$dir" >> $GITHUB_ENV;
          echo "tag=$tag" >> $GITHUB_ENV;

          sed -i -re \
            "s@features/cuda(:[0-9]+)\": \{\}@features/cuda\1\": \{\"cudaVersion\": \"${CUDA#cuda}\"\}@" \
            "./src/${dir}/.devcontainer/devcontainer.json";
          sed -i -re \
            "s@features/llvm(:[0-9]+)\": \{\}@features/llvm\1\": \{\"llvmVersion\": \"${LLVM#llvm}\"\}@" \
            "./src/${dir}/.devcontainer/devcontainer.json";
          sed -i -re \
            "s@features/nvhpc(:[0-9]+)\": \{\}@features/nvhpc\1\": \{\"nvhpcVersion\": \"${NVHPC#nvhpc}\"\}@" \
            "./src/${dir}/.devcontainer/devcontainer.json";

          echo "image name: ghcr.io/${{ github.repository }}:${tag}";
          echo "devcontainer.json:";
          cat "./src/${dir}/.devcontainer/devcontainer.json";

      - name: Set up QEMU
        if: env.build_image == '1'
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        if: env.build_image == '1'
        uses: docker/setup-buildx-action@v1
        with:
          use: true

      - name: Login to ghcr.io
        if: env.build_image == '1'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push devcontainer
        if: env.build_image == '1'
        uses: devcontainers/ci@v0.2
        with:
          push: filter
          skipContainerUserIdUpdate: true
          refFilterForPush: refs/heads/main
          eventFilterForPush: workflow_dispatch
          imageTag: ${{ env.tag }}
          subFolder: src/${{ env.dir }}
          platform: linux/amd64,linux/arm64
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}:${{ env.tag }}
