name: Publish images

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: publish-images-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish-images:
    name: Publish image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CUDA: ["", "11.8", "12.0"]
        LLVM: ["", "13", "14", "15", "dev"]
        NVHPC: ["", "22.11"]
        MAMBA: [""]
        exclude:
          - { CUDA: "11.8", LLVM: "", NVHPC: "22.11" }
          - { CUDA: "11.8", LLVM: "", NVHPC: "22.11" }
          - { CUDA: "11.8", LLVM: "", NVHPC: "22.11" }
          - { CUDA: "11.8", LLVM: "", NVHPC: "22.11" }
          - { CUDA: "12.0", LLVM: "", NVHPC: "22.11" }
          - { CUDA: "12.0", LLVM: "", NVHPC: "22.11" }
          - { CUDA: "12.0", LLVM: "", NVHPC: "22.11" }
          - { CUDA: "12.0", LLVM: "", NVHPC: "22.11" }
        include:
          - { CUDA: "", LLVM: "13", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "", LLVM: "14", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "", LLVM: "15", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "", LLVM: "dev", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "11.8", LLVM: "13", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "11.8", LLVM: "14", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "11.8", LLVM: "15", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "11.8", LLVM: "dev", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "12.0", LLVM: "13", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "12.0", LLVM: "14", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "12.0", LLVM: "15", NVHPC: "", MAMBA: "mambaforge" }
          - { CUDA: "12.0", LLVM: "dev", NVHPC: "", MAMBA: "mambaforge" }
    steps:
      - name: Checkout stdexec
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Check repo name
        shell: bash
        env:
          CUDA: "${{ matrix.CUDA }}"
          LLVM: "${{ matrix.LLVM }}"
          NVHPC: "${{ matrix.NVHPC }}"
          MAMBA: "${{ matrix.MAMBA }}"
        run: |
          cuda=${CUDA:+"-cuda"}
          llvm=${LLVM:+"-llvm"}
          nvhpc=${NVHPC:+"-nvhpc"}
          mamba=${MAMBA:+"-mambaforge"}
          dir="cmake-ninja-sccache${llvm}${cuda}${mamba}${nvhpc}"

          if [[ ! -d "./src/${dir}" ]]; then
            echo "skipping because ! -d ./src/${dir}";
            echo "build_image=0" >> $GITHUB_ENV;
            exit 0;
          fi

          echo "build_image=1" >> $GITHUB_ENV;

          cuda=${CUDA:+"-cuda${CUDA}"}
          llvm=${LLVM:+"-llvm${LLVM}"}
          nvhpc=${NVHPC:+"-nvhpc${NVHPC}"}
          mamba=${MAMBA:+"-mambaforge"}
          tag="cmake-ninja-sccache${llvm}${cuda}${nvhpc}${mamba}"
          tag="${tag:-latest}"

          echo "dir=$dir" >> $GITHUB_ENV;
          echo "tag=$tag" >> $GITHUB_ENV;

          sed -i -re \
            's@features/cuda(:[0-9]+)": \{\}@features/cuda\1": \{"cudaVersion": "${{ matrix.CUDA }}"\}@' \
            "./src/${dir}/.devcontainer/devcontainer.json";
          sed -i -re \
            's@features/llvm(:[0-9]+)": \{\}@features/llvm\1": \{"llvmVersion": "${{ matrix.LLVM }}"\}@' \
            "./src/${dir}/.devcontainer/devcontainer.json";
          sed -i -re \
            's@features/nvhpc(:[0-9]+)": \{\}@features/nvhpc\1": \{"nvhpcVersion": "${{ matrix.NVHPC }}"\}@' \
            "./src/${dir}/.devcontainer/devcontainer.json";

          echo "image name: ghcr.io/${{ github.repository }}:${tag}";
          echo "devcontainer.json:";
          cat "./src/${dir}/.devcontainer/devcontainer.json";

      - name: Set up QEMU
        if: env.build_image == '1'
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        if: env.build_image == '1'
        uses: docker/setup-buildx-action@v1
        with:
          use: true

      - name: Login to ghcr.io
        if: env.build_image == '1'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push devcontainer
        if: env.build_image == '1'
        uses: devcontainers/ci@v0.2
        with:
          push: never
          imageTag: ${{ env.tag }}
          subFolder: src/${{ env.dir }}
          platform: linux/amd64,linux/arm64
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}:${{ env.tag }}
